import { SelectOption } from "@/components/Inputs/Select/Select.types";

export interface APIStudentProfileResponse {
    studentId: string;
    userId: string;
    email: string;
    firstName: string;
    middleName: string | null;
    lastName: string;
    age?: number | null;
    sex: string;
    birthdate: string | null;
    placeOfBirth: string | null;
    mobileNumber: string | null;
    permanentStreet: string | null;
    permanentBrgyId: string | null;
    permanentCitymunId: string | null;
    permanentProvinceId: string | null;
    permanentRegionId: string | null;
    permanentZipCode: string | null;
    permanentCountry: string | null;
    currentStreet: string | null;
    currentBrgyId: string | null;
    currentCitymunId: string | null;
    currentProvinceId: string | null;
    currentRegionId: string | null;
    currentZipCode: string | null;
    currentCountry: string | null;
    isSoloParent: boolean;
    isChildOfSoloParent: boolean;
    isIndigenousPeople: boolean;
    isSped: boolean;
    isPwd: boolean;
    emergencyContactName: string | null;
    emergencyContactNumber: string | null;
    emergencyContactName2: string | null;
    emergencyContactNumber2: string | null;
    g12AcademicStrand: string | null;
    g12ProgramName: string | null;
    g12AwardHonor: string | null;
    g12Organization: string | null;
    g12YearOfGraduation: string | null;
    g12SchoolId: string | null;
    collegeProgramName: string | null;
    collegeYearLevel: string | null;
    collegeAwardHonor: string | null;
    collegeOrganization: string | null;
    collegeSchoolId: string | null;
    fatherLastName: string | null;
    fatherFirstName: string | null;
    fatherOccupation: string | null;
    fatherMobileNumber: string | null;
    motherMaidenLastName: string | null;
    motherMaidenFirstName: string | null;
    motherOccupation: string | null;
    motherMobileNumber: string | null;
    guardianLastName: string | null;
    guardianFirstName: string | null;
    guardianOccupation: string | null;
    guardianMobileNumber: string | null;
    numberOfSiblings: number | null;
    siblings: Array<string> | null;
}